### ISSUE TITLE
Add env variables

### ISSUE THREAD

**Issue by Jagerente** [GenshinAcademy/GenshinAcademySite#33]
## Цель

- Добавить переменную `VITE_LOG_LEVEL` для установки уровня логирования
- Добавить переменную `VITE_HOST_API` для установки адреса обращения к API 

Если что используются они как import.meta.env.VITE_HOST_API (.env в gitignore не забудь), берутся они либо из файла, либо из переменных окружения.

### Внести изменения в workflow:
- `/.github/workflows/build_and_deploy-dev.yaml` после 19 строчки:
```yml
      - name: Build
        env:
          VITE_HOST_API: ${{ vars.VITE_HOST_API }}
          VITE_LOG_LEVEL: ${{ vars.VITE_LOG_LEVEL }}
        run: npm run build
```
- `/.github/workflows/test_on_pr.yaml` после 23 строчки:
```yml
      - name: Test & Build
        env:
          VITE_HOST_API: ${{ vars.VITE_HOST_API }}
          VITE_LOG_LEVEL: ${{ vars.VITE_LOG_LEVEL }}
        run: npm run build
```

#### Примеры и полный файл
![Image](https://user-images.githubusercontent.com/47350537/230736088-d71457c7-efa8-463b-a81f-b091e48b1262.png)

```yml
name: Build and Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_HOST_API: ${{ vars.VITE_HOST_API }}
          VITE_LOG_LEVEL: ${{ vars.VITE_LOG_LEVEL }}
        run: npm run build

      - name: Upload artifact for deploy job
        uses: actions/upload-artifact@v3
        with:
          name: server-artifact
          path: dist/*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: server-artifact

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: '*'
          target: ${{ vars.OUTPUT_DIR_DEV }}

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl restart ${{ vars.SERVICE_NAME_DEV }}

```

![Image](https://user-images.githubusercontent.com/47350537/230736092-c9c2e71c-6e1c-4f5c-aaff-b1205e2d37a9.png)

`/.github/workflows/test_on_pr.yaml`
```yml
name: Test build on Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test & Build
        env:
          VITE_HOST_API: ${{ vars.VITE_HOST_API }}
          VITE_LOG_LEVEL: ${{ vars.VITE_LOG_LEVEL }}
        run: npm run build
```
